// ************************************************************************** //
//                                                                            //
//                                                                            //
//   registry.ts                                                              //
//                                                                            //
//   By: jeportie <jeromep.dev@gmail.com>                                     //
//                                                                            //
//   Created: 2026/01/20 15:19:43 by jeportie                                 //
//   Updated: 2026/01/20 15:34:47 by jeportie                                 //
//                                                                            //
// ************************************************************************** //

import fs from 'fs';
import path from 'path';

const REGISTRY_PATH = path.resolve('src/apiRegistry.ts');

export function ensureRegistryExists(): void {
  if (fs.existsSync(REGISTRY_PATH)) {
    return;
  }

  // Ensure src directory exists
  const srcDir = path.dirname(REGISTRY_PATH);

  if (!fs.existsSync(srcDir)) {
    fs.mkdirSync(srcDir, { recursive: true });
    console.log(`✅ Created directory: ${srcDir}`);
  }

  const content = `// ************************************************************************** //
//                                                                            //
//   apiRegistry.ts                                                           //
//                                                                            //
//   Auto-generated by Via CLI                                                //
//                                                                            //
// ************************************************************************** //

/**
 * This file augments the ApiRegistry interface from @jeportie/via
 * to add type definitions for your API endpoints.
 *
 * Each entry maps a base URL to its OpenAPI-generated types.
 */
declare module '@jeportie/via' {
  interface ApiRegistry {
    // Your API endpoints will be registered here
  }
}

export {};
`;

  fs.writeFileSync(REGISTRY_PATH, content, 'utf8');
  console.log(`✅ Created registry file: ${REGISTRY_PATH}`);
}
