// ************************************************************************** //
//                                                                            //
//                                                                            //
//   registry.ts                                                              //
//                                                                            //
//   By: jeportie <jeromep.dev@gmail.com>                                     //
//                                                                            //
//   Created: 2026/01/20 15:19:43 by jeportie                                 //
//   Updated: 2026/01/20 15:34:47 by jeportie                                 //
//                                                                            //
// ************************************************************************** //

import fs from 'fs';
import path from 'path';

const REGISTRY_PATH = path.resolve('src/apiRegistry.ts');

export function ensureRegistryExists(): void {
  if (fs.existsSync(REGISTRY_PATH)) {
    return;
  }

  const content = `
// ************************************************************************** //
//                                                                            //
//   apiRegistry.ts                                                           //
//                                                                            //
//   Auto-generated by Via CLI                                                //
//                                                                            //
// ************************************************************************** //

export interface ApiRegistry {
}
`;

  fs.writeFileSync(REGISTRY_PATH, content, 'utf8');
}
