// ************************************************************************** //
//                                                                            //
//                                                                            //
//   setup.ts                                                                 //
//                                                                            //
//   By: jeportie <jeromep.dev@gmail.com>                                     //
//                                                                            //
//   Created: 2026/01/29 18:52:33 by jeportie                                 //
//   Updated: 2026/01/29 19:12:57 by jeportie                                 //
//                                                                            //
// ************************************************************************** //

import fs from 'fs';
import path from 'path';

const SETUP_PATH = path.resolve('src/via.setup.ts');

export function ensureSetupExists(): void {
  if (fs.existsSync(SETUP_PATH)) {
    return;
  }

  // Ensure src directory exists
  const srcDir = path.dirname(SETUP_PATH);

  if (!fs.existsSync(srcDir)) {
    fs.mkdirSync(srcDir, { recursive: true });
    console.log(`✅ Created directory: ${srcDir}`);
  }

  const content = `// ************************************************************************** //
//                                                                            //
//   via.setup.ts                                                             //
//                                                                            //
//   Auto-generated by Via CLI                                                //
//                                                                            //
// ************************************************************************** //

import '@jeportie/via';
import './apiRegistry';
`;

  fs.writeFileSync(SETUP_PATH, content, 'utf8');
  console.log(`✅ Created registry file: ${SETUP_PATH}`);
}
