
// ************************************************************************** //
//                                                                            //
//   apiRegistry.ts                                                           //
//                                                                            //
//   Auto-generated by Via CLI                                                //
//                                                                            //
// ************************************************************************** //

import type { paths as petstoreSchema } from './schema/petstoreSchema.js';

export interface ApiRegistry {
  'https://petstore3.swagger.io': petstoreSchema;

}
